version: '3.8'

services:
  client:
    build: .
    image: my-client-image
    ports:
      - "3000:3000"  # Host:Container (you can change to 4000:3000 if desired)
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - REACT_APP_YOUR_HOSTNAME=http://16.170.254.164:5000
  server:
    build: .
    image: my-server-image
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0

